# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import space_escape_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('space_escape_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_image_url',
            field=models.ImageField(blank=True, null=True, upload_to=space_escape_app.models.get_image_path),
        ),
    ]
