# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_escape_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundpicture',
            name='background',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
