# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_escape_app', '0002_auto_20161213_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='next_question',
            field=models.IntegerField(default=0),
        ),
    ]
