# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_escape_app', '0003_choice_next_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='next_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_escape_app.Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='space_escape_app.Question'),
        ),
    ]
